version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install pytest
  build:
    commands:
      - pytest
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
